# Generated by Django 2.2.6 on 2019-10-24 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Enter author name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter book name', max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('book_price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('number_of_copies', models.IntegerField(default=1, help_text='number of available copies')),
                ('books_in_stock', models.IntegerField(help_text='number of books in stock')),
                ('book_description', models.TextField(help_text='overview of book')),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Enter book category', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(help_text='Enter member member id', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('member_name', models.CharField(help_text='Enter staff member name', max_length=200)),
                ('member_mobile_number', models.IntegerField(help_text='Enter member mobile number')),
                ('member_email', models.CharField(help_text='Enter member email', max_length=100)),
                ('member_address', models.CharField(help_text='Enter member address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Enter staff id', max_length=100)),
                ('staff_name', models.CharField(help_text='Enter staff name', max_length=200)),
                ('staff_mobile_number', models.IntegerField(help_text='Enter staff mobile number')),
                ('staff_email', models.CharField(help_text='Enter staff email', max_length=100)),
                ('staff_address', models.CharField(help_text='Enter staff address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField()),
                ('return_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('borrowed_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('borrowed_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
                ('issued_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BookCategory'),
        ),
    ]
